### ISSUE TITLE
Quest: Welcome to Warhammer Online! 

### ISSUE THREAD

**Issue by Rieese** [Shmerrick/ProjectWAR-Core#2]
Once you buy the Anni gear it tells you to go through the rift to speak to the recruiter. However, the rift does not do anything. Doesn't teleport to the city.

**Comment by Rieese** [comment]
Next step after talking with the Dark Recruiters has you go and talk to Seer Uresha, you have to click her name 250 times as opposed to talking with her once.

**Comment by SparkyTheOld** [comment]
Order-side you have to talk to Martial Marshal 250 times after you spoke with the Trainer

**Comment by cooler-SAI** [comment]
fixed https://github.com/Shmerrick/ProjectWAR-SQL/commit/459ec7033d8c1cfc1e75c8b83183789602e73275
