### ISSUE TITLE
Order starting zone

### ISSUE THREAD

**Issue by SparkyTheOld** [Shmerrick/ProjectWAR-Core#3]
When I log in to a fresh Order character, the second said character spawns in and is controllable it gets killed by a hostile lvl 41 Onslaught Merchant NPC unless the first thing I did is run away specifically in order to not get run down by said NPC

**Comment by cooler-SAI** [comment]
DB easy fix. Disable it

**Comment by Shmerrick** [comment]
Fixed. SQL pushed to SQL repo.
